#! /usr/bin/env sh
SCRIPT=`readlink -f "$0"`
KEYSCORE_HOME=`dirname "$SCRIPT"`

CMD="java -jar $KEYSCORE_HOME/keyscore-frontier.jar -server -XX:+UnlockExperimentalVMOptions -Xms512m -Xmx3g"

exec $CMD