:root_doc: ../../doc

= Deploying an Agent =

== Docker Container ==

The easiest and recommended way to run an Agent is to use a Docker container. You can use an official image or build your own Docker image as described
<<agent-custom-docker-image, below>>.

All important configurations to run an Agent can be passed as environment variables. So running it with Docker is very
comfortable. In the example, the seed-node host and port are passed as environment variables:

.Running the Agent as Docker container.
----
docker run --publish 3551:3551 \
           --env KEYSCORE_CLUSTER_SEED_NODE_HOST=localhost \
           --env KEYSCORE_CLUSTER_SEED_NODE_PORT=2551 \
           quay.io/logbee/keyscore-agent:0.3.0-alpha.5
----

== Zip Distribution ==

If Docker is not a option for you, don't worry. You can run an Agent like any other Java program. Get the Zip-Distribution,
extract it to a directory of your choice and start an Agent by calling the provided shell-script.

[[agent-custom-docker-image]]
== Building a custom Docker Image ==

Building your own Docker image is a simple task, because the only requirement to run an Agent inside a Docker container is a
Java Runtime Environment (JRE) of version 8. The following listing illustrates the Dockerfile we use to build the official
Docker image:

.Dockerfile
----
FROM quay.io/logbee/openjdk-8-jdk-alpine <1>

COPY distribution/ /opt/keyscore-agent/ <2>

CMD /opt/keyscore-agent/keyscore-agent <3>
----

1.  Choose your base image. If your base image does not include a JRE, install it during the docker build.
    In our case we use a base image with a pre-installed JRE.

2.  Copy the content of the zip-distribution into the Docker image. In the example above everything is copied
    to `/opt/keyscore-agent/`.

3.  At the end, specify the shell script `keyscore-agent` as command.

include::{root_doc}/docker.adoc[tags=docker-tiny-note]
