// tag::gradledocker[]
= Gradle and Docker =
By default docker requires you to use the docker command as root and therefore you have to call gradle as root whenever the specified gradle task interacts with the docker daemon.

== Manage Docker as a non-root user ==
If you don’t want to use sudo when you use the docker command, create a Unix group called docker and add users to it.
Run the following commands in your favourite shell and then *completely log out of your account and log back in* (if in doubt, reboot).
```
sudo groupadd docker
sudo gpasswd -a $USER docker
newgrp docker
```
Now you should be able to user docker as non-root user.
// end::gradledocker[]

== Docker behind a proxy ==

To run docker behind a proxy you have to configure the proxy settings at two locations.

1. To work with a docker registry through a proxy, you have to configure the <<docker-daemon-proxy-config>>.

2. To pass proxy information to containers, you have to configure the <<docker-client-proxy-config>>.

[[docker-daemon-proxy-config]]
=== Docker Daemon ===

==== OS using Systemd ====

. Create a systemd drop-in directory:
+
```
mkdir /etc/systemd/system/docker.service.d
```

. Add proxy in `/etc/systemd/system/docker.service.d/http-proxy.conf` file:
+
```
[Service]
Environment="HTTP_PROXY=https://web-proxy.corp.xxxxxx.com:8080/"
Environment="HTTPS_PROXY=https://web-proxy.corp.xxxxxx.com:8080/"
Environment="NO_PROXY=localhost,127.0.0.1,localaddress,.localdomain.com"
```

. Flush changes: `systemctl daemon-reload`
. Restart Docker: `systemctl restart docker`

==== OS using SysVinit ====

. Edit `/etc/default/docker` and add proxy configuration:
+
```
...
export http_proxy="http://web-proxy.corp.xxxxxx.com:8080/"
export https_proxy="https://web-proxy.corp.xxxxxx.com:8080/"
...
```

. Restart Docker: `service docker restart`

[[docker-client-proxy-config]]
=== Docker Client ===
Since Docker 17.07 and higher you can configure the docker client to pass proxy information to containers automatically.

Create or edit the file `~/.docker/config.json` in your home directory and add the following JSON.
```
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://web-proxy.corp.xxxxxx.com:8080",
     "httpsProxy": "http://web-proxy.corp.xxxxxx.com:8080",
     "noProxy": "*.test.example.com,.example2.com"
   }
 }
}
```
Substitute the address and port of the proxy server. You can exclude hosts or ranges by setting `noProxy` key to one or
more comma-separated IP addresses or hosts.

== Build Docker images ==
// tag::docker-tiny-note[]
[NOTE]
====
.Tiny as ENTRYPOINT

It is recommended to use https://github.com/krallin/tini[Tiny] as `ENTRYPOINT` for Docker images.
====
// end::docker-tiny-note[]

== Akka setups involving NATs ==

https://doc.akka.io/docs/akka/current/remoting.html

https://hackernoon.com/akka-cluster-in-docker-a-straight-forwards-configuration-b6deea32752d
